---
openapi: 3.0.0
info:
   version: 1.3.0
   title: fargateproduct open api specification
   description: bankform API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8014
     description: bankform
tags:
- name: bankform
paths:
   "/bankform":
      get:
         tags:
         -  bankform
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  bankform
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/bankform"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      bankform:
         type: object
         properties:
            name:
               type: "string"
               description: Description
            bankac:
               type: "string"
               description: Description